dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

jdk: openjdk8
before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.21.0/bazel_0.21.0-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.21.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.21.0-linux-x86_64.deb

script:
  - bazel test ... --test_output=all