# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_library(
    name = "Soundex",
    srcs = [
        "Soundex.h"
        ],
    hdrs = ["Soundex.h"],
    visibility = ["//visibility:public"],
)